/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.TacGia;
import Services.Impl.TacGiaService;
import Utilities.SetSize;
import java.awt.Dimension;
import java.net.URL;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 *
 * @author Admin
 */
public class FrmChonTacGia extends javax.swing.JFrame {
    final SetSize setsize = new SetSize();
    final TacGiaService SERVICE = new TacGiaService();
    /**
     * Creates new form FrmChonTacGia
     */
    public FrmChonTacGia() {
        this.setUndecorated(true);
        initComponents();
        this.seticon();
        this.setListTacGia();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtTuKhoa = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        btnChon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnListTacGia = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(311, 112));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        txtTuKhoa.setSelectionColor(new java.awt.Color(0, 0, 0));

        btnSearch.setText("jLabel1");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 40));

        btnChon.setBackground(new java.awt.Color(125, 200, 150));
        btnChon.setText("chọn");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });
        jPanel1.add(btnChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(320, 250));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(320, 250));

        pnListTacGia.setBackground(new java.awt.Color(255, 255, 255));
        pnListTacGia.setMaximumSize(new java.awt.Dimension(320, 250));
        pnListTacGia.setPreferredSize(new java.awt.Dimension(340, 250));
        jScrollPane1.setViewportView(pnListTacGia);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 400));

        btnClose.setText("jLabel1");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setPreferredSize(new java.awt.Dimension(20, 20));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:
        FrmPhieuNhap._lstTacGia = this.getLstTacGia();
        FrmSach._lstTacGia = this.getLstTacGia();
        String tacGiaChon = "";
        for (TacGia tacGia : FrmPhieuNhap._lstTacGia) {
            tacGiaChon += tacGia.getHoTen()+"-";
        }
        tacGiaChon = tacGiaChon.substring(0, tacGiaChon.length()-1);
        if(!tacGiaChon.equals("") && FrmPhieuNhap.Frm==1){
            FrmPhieuNhap.lblTacGia.setText(tacGiaChon);
            FrmPhieuNhap.Frm=0;
        }else{
            FrmSach.lblTacGia.setText(tacGiaChon);
        }
        this.dispose();
    }//GEN-LAST:event_btnChonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void seticon() {
        URL urlSearch = getClass().getResource("/Images/search.png");
        URL urldong = getClass().getResource("/Images/cross-small.png");
        btnSearch.setIcon(setsize.setSizeAnh(urlSearch, 20, 20));
        btnClose.setIcon(setsize.setSizeAnh(urldong, 20, 20));
    }
    
    private void setListTacGia(){
        FrmPhieuNhap._lstTacGia = new ArrayList<>();
        FrmSach._lstTacGia = new ArrayList<>();
        List<TacGia> _lst = SERVICE.getAll();
        _lst.sort((o1, o2) -> {
            return o1.getHoTen().compareTo(o2.getHoTen());
        });
        for (TacGia tacGia : _lst) {
            FrmTacGiaKhung frmKhung = new FrmTacGiaKhung();
            frmKhung.setDisPlayForm(tacGia);
            pnListTacGia.add(frmKhung);
        }
        int size = (pnListTacGia.getComponentCount()/3)*120 +5;
        pnListTacGia.setPreferredSize(new Dimension(WIDTH, size));
        pnListTacGia.validate();
        pnListTacGia.repaint();
    }
    
    private List<TacGia> getLstTacGia(){
        int all = pnListTacGia.getComponentCount();
        List<FrmTacGiaKhung> _lstKhung = new ArrayList<>();
        List<TacGia> _lst = new ArrayList<>();
        for (int i = 0; i < all; i++) {
            FrmTacGiaKhung frm = (FrmTacGiaKhung) pnListTacGia.getComponent(i);
            if(frm.isSelected()){
                _lstKhung.add(frm);
            }
        }
        for (FrmTacGiaKhung frmTacGiaKhung : _lstKhung) {
            _lst.add(SERVICE.getByMa(frmTacGiaKhung.getMaTacGia()));
        }
        return _lst;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnListTacGia;
    private javax.swing.JTextField txtTuKhoa;
    // End of variables declaration//GEN-END:variables
}
