/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.CuonSach;
import DomainModels.Sach;
import DomainModels.SachCT;
import Services.Impl.CuonSachService;
import Services.Impl.SachCTService;
import Services.Impl.SachService;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Admin
 */
public class FrmCapNhatTTSach extends javax.swing.JFrame {
    /**
     * Creates new form FrmCapNhatTTSach
     */
    SachService Sv_sach  = new SachService();
    SachCTService sv_sachct = new SachCTService();
    CuonSachService sv_cs = new CuonSachService();
    public FrmCapNhatTTSach() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnThongTinSach = new javax.swing.JPanel();
        pnSach1 = new javax.swing.JPanel();
        lblTenSach1 = new javax.swing.JLabel();
        cbxTinhTrang1 = new javax.swing.JComboBox<>();
        cuonSo1 = new javax.swing.JLabel();
        MS1 = new javax.swing.JLabel();
        pnSach2 = new javax.swing.JPanel();
        lblTenSach2 = new javax.swing.JLabel();
        cbxTinhTrang2 = new javax.swing.JComboBox<>();
        CuonSo2 = new javax.swing.JLabel();
        MS2 = new javax.swing.JLabel();
        pnSach3 = new javax.swing.JPanel();
        lblTenSach3 = new javax.swing.JLabel();
        cbxTinhTrang3 = new javax.swing.JComboBox<>();
        CuonSo3 = new javax.swing.JLabel();
        MS3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnXong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 230));
        setSize(new java.awt.Dimension(350, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnThongTinSach.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTinSach.setPreferredSize(new java.awt.Dimension(350, 146));
        pnThongTinSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTenSach1.setText("Tên sách 1");

        cbxTinhTrang1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "95", "90", "85", "80", "75", "70", "65", "60", "55", "50", "45", "40", "35", "30", "25", "20", "15", "10", "5", "0" }));

        cuonSo1.setText("jLabel2");

        MS1.setText("jLabel2");

        javax.swing.GroupLayout pnSach1Layout = new javax.swing.GroupLayout(pnSach1);
        pnSach1.setLayout(pnSach1Layout);
        pnSach1Layout.setHorizontalGroup(
            pnSach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSach1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(MS1)
                .addGap(18, 18, 18)
                .addComponent(lblTenSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuonSo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(cbxTinhTrang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnSach1Layout.setVerticalGroup(
            pnSach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSach1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSach1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenSach1)
                    .addComponent(cbxTinhTrang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuonSo1)
                    .addComponent(MS1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnThongTinSach.add(pnSach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        lblTenSach2.setText("Tên sách 1");

        cbxTinhTrang2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "95", "90", "85", "80", "75", "70", "65", "60", "55", "50", "45", "40", "35", "30", "25", "20", "15", "10", "5", "0" }));

        CuonSo2.setText("jLabel2");

        MS2.setText("jLabel2");

        javax.swing.GroupLayout pnSach2Layout = new javax.swing.GroupLayout(pnSach2);
        pnSach2.setLayout(pnSach2Layout);
        pnSach2Layout.setHorizontalGroup(
            pnSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSach2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(MS2)
                .addGap(18, 18, 18)
                .addComponent(lblTenSach2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CuonSo2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(cbxTinhTrang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnSach2Layout.setVerticalGroup(
            pnSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSach2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSach2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenSach2)
                    .addComponent(cbxTinhTrang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CuonSo2)
                    .addComponent(MS2))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnThongTinSach.add(pnSach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 340, -1));

        lblTenSach3.setText("Tên sách 1");

        cbxTinhTrang3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "95", "90", "85", "80", "75", "70", "65", "60", "55", "50", "45", "40", "35", "30", "25", "20", "15", "10", "5", "0" }));

        CuonSo3.setText("jLabel2");

        MS3.setText("jLabel2");

        javax.swing.GroupLayout pnSach3Layout = new javax.swing.GroupLayout(pnSach3);
        pnSach3.setLayout(pnSach3Layout);
        pnSach3Layout.setHorizontalGroup(
            pnSach3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSach3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(MS3)
                .addGap(18, 18, 18)
                .addComponent(lblTenSach3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CuonSo3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(cbxTinhTrang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnSach3Layout.setVerticalGroup(
            pnSach3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSach3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSach3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenSach3)
                    .addComponent(cbxTinhTrang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CuonSo3)
                    .addComponent(MS3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnThongTinSach.add(pnSach3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 340, 40));

        jPanel1.add(pnThongTinSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 340, 122));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cập nhật tình trạng");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 0, -1, -1));

        btnXong.setText("Xong");
        btnXong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXongActionPerformed(evt);
            }
        });
        jPanel1.add(btnXong, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 166, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXongActionPerformed
        // TODO add your handling code here:
        int cso = pnThongTinSach.getComponentCount();
        for (int i = 0; i < cso; i++) {
            CuonSach cs = new CuonSach();
            switch (i) {
                case 0 ->                     {
                        Sach sach = Sv_sach.getByMa(MS1.getText());
                        SachCT sachct = sv_sachct.getByIDSach(sach.getId());
                        cs = sv_cs.getByMaAndID(sachct.getId(), cuonSo1.getText());
                        cs.setTinhTrang(Float.valueOf(cbxTinhTrang1.getSelectedItem()+""));
                    }
                case 1 ->                     {
                        Sach sach = Sv_sach.getByMa(MS2.getText());
                        SachCT sachct = sv_sachct.getByIDSach(sach.getId());
                        cs = sv_cs.getByMaAndID(sachct.getId(), CuonSo2.getText());
                        cs.setTinhTrang(Float.valueOf(cbxTinhTrang2.getSelectedItem()+""));
                    }
                case 2 ->                     {
                        System.out.println(MS3.getText());
                        Sach sach = Sv_sach.getByMa(MS3.getText());
                        SachCT sachct = sv_sachct.getByIDSach(sach.getId());
                        cs = sv_cs.getByMaAndID(sachct.getId(), CuonSo3.getText());
                        cs.setTinhTrang(Float.valueOf(cbxTinhTrang3.getSelectedItem()+""));
                    }
            }
            cs.setTrangThai(true);
            sv_cs.update(cs);
        }
        this.dispose();
    }//GEN-LAST:event_btnXongActionPerformed

    
    public void setDisplay(List<Sach> _lstSach, List<CuonSach> _lstCuonSach){
        int Cs = 0;
        for (Sach sach : _lstSach) {
            String i = _lstCuonSach.get(Cs).getTinhTrang()+"";
            i = i.substring(0, i.length()-2);
            switch (Cs) {
                case 0 -> {
                    lblTenSach1.setText(sach.getTen());
                    cuonSo1.setText(_lstCuonSach.get(Cs).getMa()+"");
                    MS1.setText(sach.getMa());
                    cbxTinhTrang1.setSelectedItem(i);
                }
                case 1 -> {
                    lblTenSach2.setText(sach.getTen());
                    CuonSo2.setText(_lstCuonSach.get(Cs).getMa()+"");
                    MS2.setText(sach.getMa());
                    cbxTinhTrang2.setSelectedItem(i);
                }
                case 2 -> {
                    lblTenSach3.setText(sach.getTen());
                    CuonSo3.setText(_lstCuonSach.get(Cs).getMa()+"");
                    MS3.setText(sach.getMa());
                    cbxTinhTrang3.setSelectedItem(i);
                }
            }
            Cs++;
        }
    }
    
    public  void getSL(int sl){
        int i = pnThongTinSach.getComponentCount();
        for (int j = i; j >sl ; j--) {
            pnThongTinSach.remove(j-1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CuonSo2;
    private javax.swing.JLabel CuonSo3;
    private javax.swing.JLabel MS1;
    private javax.swing.JLabel MS2;
    private javax.swing.JLabel MS3;
    private javax.swing.JButton btnXong;
    private javax.swing.JComboBox<String> cbxTinhTrang1;
    private javax.swing.JComboBox<String> cbxTinhTrang2;
    private javax.swing.JComboBox<String> cbxTinhTrang3;
    private javax.swing.JLabel cuonSo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTenSach1;
    private javax.swing.JLabel lblTenSach2;
    private javax.swing.JLabel lblTenSach3;
    private javax.swing.JPanel pnSach1;
    private javax.swing.JPanel pnSach2;
    private javax.swing.JPanel pnSach3;
    private javax.swing.JPanel pnThongTinSach;
    // End of variables declaration//GEN-END:variables
}
