/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import DomainModels.DocGia;
import Services.Impl.DocGiaService;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class FrmDocGiaKhung extends javax.swing.JPanel {
    final DocGiaService service = new DocGiaService();
    public FrmDocGiaKhung() {
        initComponents();
    }
    
    public void setFrm(String ten, String diaChi, String ma, String icon){
        lblMa.setText(ma);
        lblDiaChi.setText(diaChi);
        lblTen.setText(ten);
        ImageIcon img = new ImageIcon(icon);
        Image imgrs = img.getImage();
        Image imgnew = imgrs.getScaledInstance(80, 100, java.awt.Image.SCALE_SMOOTH);
        lblImg.setIcon(new ImageIcon(imgnew));
    }
    
    public boolean checkChk(){
        return chkDuocChon.isSelected();
    }
    
    public String getMa(){
        return lblMa.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        btnXemThongTin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        chkDuocChon = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(176, 212, 184));
        setMinimumSize(new java.awt.Dimension(350, 110));
        setPreferredSize(new java.awt.Dimension(350, 110));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );

        add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 100));

        lblTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTen.setText("Nguyễn Công Thuần");
        add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setText("Mã:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        lblMa.setText("PH26631");
        add(lblMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, -1));

        jLabel4.setText("Địa chỉ:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 50, -1));

        lblDiaChi.setText("Hà Nội");
        add(lblDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 190, -1));

        btnXemThongTin.setBackground(new java.awt.Color(234, 231, 214));
        btnXemThongTin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        btnXemThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXemThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXemThongTinMouseClicked(evt);
            }
        });

        jLabel6.setText("Xem thông tin");
        btnXemThongTin.add(jLabel6);

        add(btnXemThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 100, -1));

        chkDuocChon.setBackground(new java.awt.Color(176, 212, 184));
        chkDuocChon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(chkDuocChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXemThongTinMouseClicked
        // TODO add your handling code here:
        String ma = lblMa.getText();
        DocGia docgia = service.getByMa(ma);
        FrmDocGia docgiarm = new FrmDocGia();
        docgiarm.setEdit();
        docgiarm.setDisplay(docgia);
        docgiarm.setVisible(true);
    }//GEN-LAST:event_btnXemThongTinMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnXemThongTin;
    public javax.swing.JCheckBox chkDuocChon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblImg;
    public javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblTen;
    private javax.swing.JPanel pn;
    // End of variables declaration//GEN-END:variables
}
