/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Services.Impl.DangNhapService;
import Utilities.SetSize;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FrmLogin extends javax.swing.JFrame {
    DangNhapService SERVICE = new DangNhapService();
    SetSize setsize = new SetSize();
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.seticon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        chkNhoTaiKhoan = new javax.swing.JCheckBox();
        lblQuenMatKhau = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management");
        setMaximumSize(new java.awt.Dimension(960, 510));
        setPreferredSize(new java.awt.Dimension(1060, 510));

        jPanel1.setBackground(new java.awt.Color(125, 180, 125));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));

        jPanel3.setBackground(new java.awt.Color(125, 180, 125));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Welcome to FPL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(125, 180, 125));
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 200));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 150));

        jPanel5.setBackground(new java.awt.Color(125, 180, 125));
        jPanel5.setMinimumSize(new java.awt.Dimension(68, 46));
        jPanel5.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel5.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tài khoản");
        jPanel5.add(jLabel2, java.awt.BorderLayout.CENTER);

        txtTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTaiKhoan.setPreferredSize(new java.awt.Dimension(64, 28));
        txtTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaiKhoanActionPerformed(evt);
            }
        });
        jPanel5.add(txtTaiKhoan, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(125, 180, 125));
        jPanel6.setMinimumSize(new java.awt.Dimension(68, 46));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel6.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mật khẩu");
        jPanel6.add(jLabel3, java.awt.BorderLayout.CENTER);

        txtMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMatKhau.setPreferredSize(new java.awt.Dimension(64, 28));
        jPanel6.add(txtMatKhau, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel6);

        jPanel8.setBackground(new java.awt.Color(125, 180, 125));
        jPanel8.setMinimumSize(new java.awt.Dimension(250, 150));
        jPanel8.setPreferredSize(new java.awt.Dimension(250, 32));
        jPanel8.setLayout(new java.awt.BorderLayout());

        chkNhoTaiKhoan.setBackground(new java.awt.Color(125, 180, 125));
        chkNhoTaiKhoan.setText("Nhớ tài khoản");
        chkNhoTaiKhoan.setToolTipText("");
        chkNhoTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkNhoTaiKhoan.setMargin(new java.awt.Insets(2, 0, 2, 0));
        chkNhoTaiKhoan.setMaximumSize(new java.awt.Dimension(98, 24));
        chkNhoTaiKhoan.setMinimumSize(new java.awt.Dimension(98, 24));
        chkNhoTaiKhoan.setPreferredSize(new java.awt.Dimension(100, 24));
        jPanel8.add(chkNhoTaiKhoan, java.awt.BorderLayout.WEST);

        lblQuenMatKhau.setForeground(new java.awt.Color(161, 26, 30));
        lblQuenMatKhau.setText("Quên mật khẩu?");
        lblQuenMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseClicked(evt);
            }
        });
        jPanel8.add(lblQuenMatKhau, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel8);

        jPanel1.add(jPanel4);

        jPanel7.setBackground(new java.awt.Color(125, 180, 125));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 50));

        btnLogin.setBackground(new java.awt.Color(125, 220, 125));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setPreferredSize(new java.awt.Dimension(250, 28));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoginMousePressed(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel7.add(btnLogin);

        jPanel1.add(jPanel7);

        jPanel9.setBackground(new java.awt.Color(125, 180, 125));
        jPanel9.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel1.add(jPanel9);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background-loginh.jpg"))); // NOI18N
        jPanel2.add(jLabel7);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaiKhoanActionPerformed

    private void seticon(){
        URL url = getClass().getResource("/Images/iconTrangchu.png");
        ImageIcon imgi = setsize.setSizeAnh(url, 24, 24);
        Image img = imgi.getImage();
        this.setIconImage(img);
    }
    private void lblQuenMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseClicked
        // TODO add your handling code here:
        FrmQuenMatKhau quen = new FrmQuenMatKhau();
        quen.setVisible(true);
    }//GEN-LAST:event_lblQuenMatKhauMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
//        String taiKhoan = txtTaiKhoan.getText();
//        char[] args= txtMatKhau.getPassword();
//        String matKhau = "";
//        for (char arg : args) {
//            matKhau+=arg;
//        }
//        int check = SERVICE.login(taiKhoan, matKhau);
//        if(check==1){
            this.dispose();
            FrmChinh frm = new FrmChinh();
            frm.setVisible(true);
//            return;
//        }
//        JOptionPane.showMessageDialog(this, "Sai tên tài khoản hoặc mật khẩu!");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkNhoTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
