/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.NhaXuatBan;
import Services.Impl.NhaXuatBanService;
import Utilities.SetSize;
import java.awt.Color;
import java.net.URL;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Admin
 */
public class FrmNhaXuatBan extends javax.swing.JFrame {

    final SetSize setsize = new SetSize();
    final static NhaXuatBanService SERVICE = new NhaXuatBanService();

    /**
     * Creates new form FrmNhaXuatBan
     */
    public FrmNhaXuatBan() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.seticon();
        this.setTable();
        this.loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        btnHoanThanh = new javax.swing.JButton();
        btnClose = new javax.swing.JLabel();
        rdoThem = new javax.swing.JRadioButton();
        rdoSua = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhaXuaBan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nhà xuất bản");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        jLabel2.setText("Tên");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 70, 46, -1));

        jLabel3.setText("Địa chỉ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 70, 46, -1));
        jPanel2.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 67, 100, -1));
        jPanel2.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 67, 100, -1));

        btnHoanThanh.setBackground(new java.awt.Color(125, 200, 150));
        btnHoanThanh.setText("Hoàn thành");
        btnHoanThanh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoanThanhActionPerformed(evt);
            }
        });
        jPanel2.add(btnHoanThanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 107, -1, -1));

        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setPreferredSize(new java.awt.Dimension(20, 20));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 7, 22, -1));

        rdoThem.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoThem);
        rdoThem.setSelected(true);
        rdoThem.setText("Thêm");
        jPanel2.add(rdoThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 108, -1, -1));

        rdoSua.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoSua);
        rdoSua.setText("Sửa");
        jPanel2.add(rdoSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 108, -1, -1));

        jLabel4.setText("ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 33, 46, -1));

        lblID.setText("IS AUTO");
        jPanel2.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 33, 270, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblNhaXuaBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tên NXB", "Địa Chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhaXuaBan.setGridColor(new java.awt.Color(255, 255, 255));
        tblNhaXuaBan.setSelectionBackground(new java.awt.Color(125, 200, 150));
        tblNhaXuaBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhaXuaBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhaXuaBan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 158, 350, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
        FrmChinh.setFrmChinh(new FrmQuanLyKhoSach());
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanThanhActionPerformed
        // TODO add your handling code here:
        NhaXuatBan nxb = getFormData();
        if(rdoThem.isSelected()){
            SERVICE.insert(nxb, this);
        }else{
            String id = lblID.getText();
            if(id.equalsIgnoreCase("IS AUTO")){
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà xuất bản để tiếp tục!");
                return;
            }
            nxb.setId(id);
            SERVICE.update(nxb, this);
        }
        this.loadTable();
        this.clear();
    }//GEN-LAST:event_btnHoanThanhActionPerformed

    private void tblNhaXuaBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhaXuaBanMouseClicked
        // TODO add your handling code here:
        int row = tblNhaXuaBan.getSelectedRow();
        NhaXuatBan nxb = SERVICE.getByID((String) tblNhaXuaBan.getValueAt(row, 0));
        txtTen.setText(nxb.getTen());
        lblID.setText(nxb.getId());
        txtDiaChi.setText(nxb.getDiaChi());
    }//GEN-LAST:event_tblNhaXuaBanMouseClicked

    private NhaXuatBan getFormData(){
        String ten = txtTen.getText();
        String diaChi = txtDiaChi.getText();
        return new NhaXuatBan(null, ten, diaChi);
    }
    
    private void loadTable(){
        DefaultTableModel model = (DefaultTableModel) tblNhaXuaBan.getModel();
        model.setRowCount(0);
        List<NhaXuatBan> _lst = SERVICE.getAll();
        for (NhaXuatBan nhaXuatBan : _lst) {
            Object rowData[] = {
                nhaXuatBan.getId(), nhaXuatBan.getTen(), nhaXuatBan.getDiaChi()
            };
            model.addRow(rowData);
        }
        tblNhaXuaBan.setModel(model);
    }
    public void clear() {
        txtTen.setText("");
        txtDiaChi.setText("");
        lblID.setText("IS AUTO");
    }
    private void seticon() {
        URL urldong = getClass().getResource("/Images/cross-small.png");
        btnClose.setIcon(setsize.setSizeAnh(urldong, 20, 20));
    }
    
    private void setTable() {
        JTableHeader header = tblNhaXuaBan.getTableHeader();
        header.setBackground(new Color(125, 200, 150));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnHoanThanh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JRadioButton rdoSua;
    private javax.swing.JRadioButton rdoThem;
    private javax.swing.JTable tblNhaXuaBan;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
