/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.NhaCC;
import Services.Impl.NhaCCService;
import Utilities.DBConnection;
import Utilities.SetSize;
import java.awt.Color;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Admin
 */
public class FrmNhaCungCap extends javax.swing.JFrame {
    final SetSize setsize = new SetSize();
    final static NhaCCService SERVICE = new NhaCCService();
    /**
     * Creates new form FrmNhaCungCap
     */
    public FrmNhaCungCap() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.seticon();
        this.loadTable();
        this.setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        btnHoanThanh = new javax.swing.JButton();
        btnClose = new javax.swing.JLabel();
        rdthem = new javax.swing.JRadioButton();
        rdsua = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNCC = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(396, 410));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nhà cung cấp");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("Tên");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 46, -1));

        jLabel3.setText("Địa chỉ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 46, -1));
        jPanel2.add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 77, 130, -1));
        jPanel2.add(txtdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 117, 130, -1));

        btnHoanThanh.setBackground(new java.awt.Color(125, 200, 150));
        btnHoanThanh.setText("Hoàn thành");
        btnHoanThanh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoanThanhActionPerformed(evt);
            }
        });
        jPanel2.add(btnHoanThanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setPreferredSize(new java.awt.Dimension(20, 20));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 0, 20, 20));

        rdthem.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdthem);
        rdthem.setSelected(true);
        rdthem.setText("Thêm");
        jPanel2.add(rdthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        rdsua.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdsua);
        rdsua.setText("Sửa");
        jPanel2.add(rdsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel5.setText("SDT");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 40, -1));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 117, 130, -1));

        jLabel6.setText("Email");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 40, -1));
        jPanel2.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 77, 130, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "TÊN NHÀ CC", "ĐỊA CHỈ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNCC.setGridColor(new java.awt.Color(255, 255, 255));
        tblNCC.setSelectionBackground(new java.awt.Color(125, 200, 150));
        tblNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNCC);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 210, 385, 190));

        jLabel4.setText("ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 30, -1));

        lblID.setText("IS AUTO");
        jPanel2.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
        FrmChinh.setFrmChinh(new FrmQuanLyKhoSach());
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanThanhActionPerformed
        NhaCC ncc = getFromData();
        if(rdthem.isSelected()){
            SERVICE.Insert(ncc, this);
        }else{
            String id = lblID.getText();
            String mess = id.equals("IS AUTO")?"Vui lòng chọn nhà cung cấp để tiếp tục":"";
            if(!mess.equals("")){
                JOptionPane.showMessageDialog(this, mess);
                return;
            }
            ncc.setId(id);
            SERVICE.Update(ncc, this);
        }
        this.clearForm();
        this.loadTable();
    }//GEN-LAST:event_btnHoanThanhActionPerformed

    private void tblNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNCCMouseClicked
        // TODO add your handling code here:
        int row = tblNCC.getSelectedRow();
        NhaCC ncc = SERVICE.getByID((String) tblNCC.getValueAt(row, 0));
        lblID.setText(ncc.getId());
        txtten.setText(ncc.getTen());
        txtdiachi.setText(ncc.getDiaChi());
        txtSDT.setText(ncc.getSdt());
        txtEmail.setText(ncc.getEmail());
    }//GEN-LAST:event_tblNCCMouseClicked

    private NhaCC getFromData(){
        String ten = txtten.getText();
        String diaChi = txtdiachi.getText();
        String sdt = txtSDT.getText();
        String email = txtEmail.getText();
        return new NhaCC(null, ten, diaChi, sdt, email);
    }
    private void seticon(){
        URL urldong = getClass().getResource("/Images/cross-small.png");
        btnClose.setIcon(setsize.setSizeAnh(urldong, 20, 20));
    }
    
    private void loadTable(){
        DefaultTableModel model = (DefaultTableModel) tblNCC.getModel();
        model.setRowCount(0);
        List<NhaCC> _lst = SERVICE.getAll();
        for (NhaCC nhaCC : _lst) {
            Object rowDate[]={
                nhaCC.getId(), nhaCC.getTen(), nhaCC.getDiaChi()
            };
            model.addRow(rowDate);
        }
        tblNCC.setModel(model);
    }
    
    private void setTable() {
        JTableHeader header = tblNCC.getTableHeader();
        header.setBackground(new Color(125, 200, 150));
    }
    
    private void clearForm(){
        lblID.setText("IS AUTO");
        txtten.setText("");
        txtdiachi.setText("");
        txtEmail.setText("");
        txtSDT.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnHoanThanh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JRadioButton rdsua;
    private javax.swing.JRadioButton rdthem;
    private javax.swing.JTable tblNCC;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
