/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.CuonSach;
import DomainModels.NhaCC;
import DomainModels.NhaXuatBan;
import DomainModels.PhieuNhap;
import DomainModels.Sach;
import DomainModels.SachCT;
import DomainModels.TacGia;
import DomainModels.TheLoaiSach;
import Services.Impl.CuonSachService;
import Services.Impl.NhaCCService;
import Services.Impl.NhaXuatBanService;
import Services.Impl.PhieuNhapService;
import Services.Impl.PhieuNhapViewModelService;
import Services.Impl.SachCTService;
import Services.Impl.SachService;
import Services.Impl.TacGiaService;
import Services.Impl.TheLoaiService;
import Utilities.SetSize;
import ViewModels.PhieuNhapViewmodel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.io.File;
import java.math.BigDecimal;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.net.URL;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Admin
 */
public class FrmPhieuNhap extends javax.swing.JFrame {
    final SetSize setsize = new SetSize();
    final PhieuNhapService SERVICE = new PhieuNhapService();
    final SachService SERVICE_SACH = new SachService();
    final SachCTService SERVICE_SACHCT = new SachCTService();
    final TheLoaiService SERVICE_TLS = new TheLoaiService();
    final TacGiaService SERVICE_TG = new TacGiaService();
    final NhaXuatBanService SERVICE_NXB = new NhaXuatBanService();
    final PhieuNhapViewModelService SERVICE_VIEW = new PhieuNhapViewModelService();
    final CuonSachService SERVICE_CS = new CuonSachService();
    final NhaCCService SERVICE_NCC = new NhaCCService();
    JTextField txtSoLuong = new JTextField();
    static int ipn =20000;
    static int isach = 20000;
    static int suaAnh = 0;
    static String icon = "";
    final SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    public static List<TacGia> _lstTacGia = new ArrayList<>();
    public static int Frm = 0;
    /**
     * Creates new form NewJFrame
     */
    public FrmPhieuNhap() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.seticon();
        fillCbxNXB();
        fillCbxNCC();
        fillChkTL();
        this.setNgayNhap();
    }

    private void seticon(){
        URL urldong = getClass().getResource("/Images/cross-small.png");
        btnDong.setIcon(setsize.setSizeAnh(urldong, 20, 20));
        URL urlBarcode = getClass().getResource("/Images/barcode-read.png");
        IconBarcode.setIcon(setsize.setSizeAnh(urlBarcode, 24, 28));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnPhieuNhap = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblToday = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdoDaCo = new javax.swing.JRadioButton();
        rdoChuaCo = new javax.swing.JRadioButton();
        btnDong = new javax.swing.JLabel();
        btnQuanLyThongTin = new javax.swing.JButton();
        PnThongTinSach = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSoLuongNhap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        boxTheLoai = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        txtNamXuatBan = new javax.swing.JTextField();
        btnHoanThanh = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        imgAnhSach = new javax.swing.JLabel();
        btnTaiAnh = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cbxNCC = new javax.swing.JComboBox<>();
        btnTacGia = new javax.swing.JButton();
        lblTacGia = new javax.swing.JLabel();
        cbxNhaXuatBan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblSeri = new javax.swing.JLabel();
        IconBarcode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnPhieuNhap.setBackground(new java.awt.Color(255, 255, 255));
        pnPhieuNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 200, 150)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Phiếu nhập");

        lblToday.setText("14:09, 10-11-2022");

        jLabel4.setText("ID:");

        lblID.setText("IS ID");

        jLabel6.setText("Tình trạng:");

        rdoDaCo.setBackground(new java.awt.Color(255, 255, 255));
        rdoDaCo.setSelected(true);
        rdoDaCo.setText("Đã có");
        rdoDaCo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoDaCo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoDaCoMouseClicked(evt);
            }
        });
        rdoDaCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDaCoActionPerformed(evt);
            }
        });

        rdoChuaCo.setBackground(new java.awt.Color(255, 255, 255));
        rdoChuaCo.setSelected(true);
        rdoChuaCo.setText("Chưa có");
        rdoChuaCo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoChuaCo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoChuaCoMouseClicked(evt);
            }
        });

        btnDong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDong.setPreferredSize(new java.awt.Dimension(22, 22));
        btnDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDongMouseClicked(evt);
            }
        });

        btnQuanLyThongTin.setBackground(new java.awt.Color(125, 200, 150));
        btnQuanLyThongTin.setText("Quản lý thông tin");
        btnQuanLyThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyThongTinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPhieuNhapLayout = new javax.swing.GroupLayout(pnPhieuNhap);
        pnPhieuNhap.setLayout(pnPhieuNhapLayout);
        pnPhieuNhapLayout.setHorizontalGroup(
            pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPhieuNhapLayout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(214, 214, 214)
                .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnPhieuNhapLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPhieuNhapLayout.createSequentialGroup()
                        .addGroup(pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPhieuNhapLayout.createSequentialGroup()
                                .addComponent(rdoDaCo)
                                .addGap(18, 18, 18)
                                .addComponent(rdoChuaCo))
                            .addGroup(pnPhieuNhapLayout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnQuanLyThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblToday))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnPhieuNhapLayout.setVerticalGroup(
            pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhieuNhapLayout.createSequentialGroup()
                .addGroup(pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPhieuNhapLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblToday, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblID)
                    .addComponent(btnQuanLyThongTin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdoDaCo)
                    .addComponent(rdoChuaCo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 112));

        PnThongTinSach.setBackground(new java.awt.Color(255, 255, 255));
        PnThongTinSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 200, 150)));
        PnThongTinSach.setPreferredSize(new java.awt.Dimension(580, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Thông tin sách nhập");

        jLabel7.setText("Mã sách");
        jLabel7.setPreferredSize(new java.awt.Dimension(75, 16));

        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachActionPerformed(evt);
            }
        });

        jLabel8.setText("Tên sách");
        jLabel8.setPreferredSize(new java.awt.Dimension(75, 16));

        jLabel9.setText("Tác giả");
        jLabel9.setPreferredSize(new java.awt.Dimension(75, 16));

        jLabel10.setText("Số lượng");
        jLabel10.setPreferredSize(new java.awt.Dimension(75, 16));

        jLabel11.setText("Nhà xuất bản");
        jLabel11.setPreferredSize(new java.awt.Dimension(75, 16));

        jLabel12.setText("Thể loại");
        jLabel12.setPreferredSize(new java.awt.Dimension(75, 16));

        jLabel13.setText("Năm xuất bản");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        boxTheLoai.setBackground(new java.awt.Color(255, 255, 255));
        boxTheLoai.setMaximumSize(new java.awt.Dimension(185, 900));
        boxTheLoai.setMinimumSize(new java.awt.Dimension(185, 30));
        boxTheLoai.setPreferredSize(new java.awt.Dimension(185, 100));
        boxTheLoai.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Tâm lý");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        boxTheLoai.add(jCheckBox1);

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Khoa học-viễn tưởng");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        boxTheLoai.add(jCheckBox2);

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Tình cảm");
        boxTheLoai.add(jCheckBox3);

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Kinh doanh - kinh tế");
        boxTheLoai.add(jCheckBox4);

        jScrollPane1.setViewportView(boxTheLoai);

        btnHoanThanh.setBackground(new java.awt.Color(125, 200, 150));
        btnHoanThanh.setText("Hoàn thành");
        btnHoanThanh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoanThanhActionPerformed(evt);
            }
        });

        jLabel15.setText("Giá nhập");
        jLabel15.setPreferredSize(new java.awt.Dimension(75, 16));

        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgAnhSach, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgAnhSach, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );

        btnTaiAnh.setBackground(new java.awt.Color(125, 200, 150));
        btnTaiAnh.setText("Tải ảnh");
        btnTaiAnh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTaiAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiAnhActionPerformed(evt);
            }
        });

        jLabel14.setText("Nhà cung cấp");
        jLabel14.setPreferredSize(new java.awt.Dimension(75, 16));

        cbxNCC.setBackground(new java.awt.Color(125, 200, 150));
        cbxNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTacGia.setBackground(new java.awt.Color(125, 200, 150));
        btnTacGia.setText("Chọn");
        btnTacGia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacGiaActionPerformed(evt);
            }
        });

        lblTacGia.setText("-----");

        cbxNhaXuatBan.setBackground(new java.awt.Color(125, 200, 150));
        cbxNhaXuatBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Seri:");
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 16));

        lblSeri.setText("Is seri");

        IconBarcode.setText("jLabel17");
        IconBarcode.setPreferredSize(new java.awt.Dimension(24, 24));
        IconBarcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconBarcodeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PnThongTinSachLayout = new javax.swing.GroupLayout(PnThongTinSach);
        PnThongTinSach.setLayout(PnThongTinSachLayout);
        PnThongTinSachLayout.setHorizontalGroup(
            PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                                .addComponent(btnTacGia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTacGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbxNhaXuatBan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                                .addGap(0, 107, Short.MAX_VALUE))))
                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnTaiAnh)
                        .addGap(37, 37, 37)
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnHoanThanh)
                                            .addComponent(lblSeri, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(IconBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxNCC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        PnThongTinSachLayout.setVerticalGroup(
            PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTacGia))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTacGia)
                        .addGap(16, 16, 16)
                        .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaiAnh)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeri)
                    .addComponent(IconBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHoanThanh)
                .addGap(33, 33, 33))
        );

        jPanel1.add(PnThongTinSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 580, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoDaCoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoDaCoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rdoDaCoMouseClicked

    private void rdoChuaCoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoChuaCoMouseClicked
        // TODO add your handling code here:
        this.checkSach(true);
        txtMaSach.setText("is auto");
        txtMaSach.setEditable(false);
    }//GEN-LAST:event_rdoChuaCoMouseClicked

    private void btnDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDongMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDongMouseClicked

    private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacGiaActionPerformed
        // TODO add your handling code here:
        Frm = 1;
        new FrmChonTacGia().setVisible(true);
    }//GEN-LAST:event_btnTacGiaActionPerformed

    private void btnHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanThanhActionPerformed
        // TODO add your handling code here:
        Sach sach;
        if(FrmKiemTraPhieuNhap.Q_A){
            String soLuong = this.txtSoLuong.getText();
            SachCT sachCT = SERVICE_SACHCT.getByBarcode(FrmScanBC.SERI);
            CuonSach cs = new CuonSach(null, 0, sachCT, 100, false);
            List<CuonSach> _lstcs= SERVICE_CS.getByIDSachCT(sachCT.getId());
            int soBatDau = _lstcs.isEmpty()?0:_lstcs.size();
            int soLuongNhap = Integer.parseInt(soLuong);
            SERVICE_CS.insert(soLuongNhap, cs, soBatDau);
            PhieuNhap pn = new PhieuNhap();
            try {
                pn = new PhieuNhap(null, this.roleMaPhieuNhap(), sachCT.getId(), sdf.parse(lblToday.getText()), true, soLuongNhap, sachCT.getGiaIn());
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            SERVICE.insert(pn);
        }else{
            Sach sachnew = getSachFormData();
            SERVICE_SACH.insert(sachnew);
            sach = SERVICE_SACH.getByMa(sachnew.getMa());
            this.insertTGCT(sach);
            this.insertTLCT(sach);
            SachCT sachCT = insertSachCT(sach);
            this.insertNXBCT(sachCT);
            this.insertCS(sachCT);
            PhieuNhap pn = getPhieuNhapFormData(sachCT.getId());
            pn.setId(null);
            pn.setTinhtrang(false);
            pn = SERVICE.insert(pn);
            this.insertNhaCCCT(pn);
            }
            this.dispose();
            FrmChinh.setFrmChinh(new FrmQuanLyKhoSach());
    }//GEN-LAST:event_btnHoanThanhActionPerformed

    private void btnTaiAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiAnhActionPerformed
        // TODO add your handling code here:
        suaAnh=1;
        JFileChooser choose = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        choose.showDialog(this, "Confirm");
        File file = choose.getSelectedFile();
        icon = file.getAbsolutePath();
        int index = icon.lastIndexOf("\\");
        icon ="/Images/imgSach/"+ icon.substring(index+1);
        URL img = getClass().getResource(icon);
        imgAnhSach.setIcon(setsize.setSizeAnh(img, 133, 162));
    }//GEN-LAST:event_btnTaiAnhActionPerformed

    private void insertTGCT(Sach sach){
        for (TacGia tacGia : _lstTacGia) {
                SERVICE_TG.insertTGCT(sach.getId(), tacGia.getId());
        }
    }
    
    private void insertTLCT(Sach sach){
        List<TheLoaiSach> _lstTLS = getListTheLoai();
        for (TheLoaiSach theLoaiSach : _lstTLS) {
            SERVICE_TLS.insertTLCT(sach.getId(), theLoaiSach.getId());
        }
    }
    
    private SachCT insertSachCT(Sach sach){
        SachCT sachctnew = getSachCTFormData(sach);
        SERVICE_SACHCT.insert(sachctnew);
        return SERVICE_SACHCT.getByIDSach(sach.getId());
    }
    
    private void insertNXBCT(SachCT sachCT){
        String nxbData = (String) cbxNhaXuatBan.getSelectedItem();
        int indexNXB = nxbData.indexOf("-");
        String tenNXB = nxbData.substring(0, indexNXB);
        String diaChiNXB = nxbData.substring(indexNXB+1);
        NhaXuatBan nxb = SERVICE_NXB.getByNameNDiaChi(tenNXB, diaChiNXB);
        SERVICE_NXB.insertNXBCT(nxb.getId(), sachCT.getId());
    }
    
    private void insertCS(SachCT sachCT){
        int soLuong = Integer.parseInt(txtSoLuongNhap.getText());
        CuonSach cs = new CuonSach(null, 0, sachCT, 100, false);
        List<CuonSach> _lstcs= SERVICE_CS.getByIDSachCT(sachCT.getId());
        int soBatDau = _lstcs.isEmpty()?0:_lstcs.size();
        SERVICE_CS.insert(soLuong, cs, soBatDau);
    }
    
    private void insertNhaCCCT(PhieuNhap pn){
        String nccData = (String) cbxNCC.getSelectedItem();
        int indexNCC = nccData.indexOf("-");
        String tenNCC = nccData.substring(0, indexNCC);
        String diaChiNCC = nccData.substring(indexNCC+1);
        NhaCC nhaCC = SERVICE_NCC.getByNameNDiaChi(tenNCC, diaChiNCC);
        SERVICE.InsertNCCCT(pn.getId(), nhaCC.getId());
    }
    public void setSachDaCo(JPanel panel){
        JPanel pn = new JPanel(new FlowLayout());
        txtSoLuong.setPreferredSize(new Dimension(200, 24));
        pnPhieuNhap.remove(this.rdoChuaCo);
        PnThongTinSach.removeAll();
        PnThongTinSach.setLayout(new FlowLayout());
        PnThongTinSach.add(panel);
        pn.add(new JLabel("Số lượng"));
        pn.add(txtSoLuong);
        pn.setBackground(Color.white);
        PnThongTinSach.add(pn);
        PnThongTinSach.add(btnHoanThanh);
        this.validate();
        this.repaint();
    }
    public void setSachChuaCo(){
        this.checkSach(true);
        txtMaSach.setText("is auto");
        txtMaSach.setEditable(false);
    }
    public void setDisplaySach(String ma, PhieuNhap pn){
        PhieuNhapViewmodel view = SERVICE_VIEW.getPhieuNhapView(ma, pn);
        txtMaSach.setText(view.getMaSach());
        txtTenSach.setText(view.getTenSach());
        String hoten="";
        for (String string : view.getTacGia()) {
            hoten += string+"-";
        }
        hoten = hoten.substring(0, hoten.length()-1);
        lblTacGia.setText(hoten);
        txtSoLuongNhap.setText(view.getSoLuong()+"");
        cbxNhaXuatBan.setSelectedItem(view.getNhaXuatBan());
        for (String string : view.getTheLoai()) {
            for (int j = 0; j < boxTheLoai.getComponentCount(); j++) {
                if(j+1==boxTheLoai.getComponentCount()){
                    break;
                }
                JCheckBox chk = (JCheckBox) boxTheLoai.getComponent(j+1);
                if(chk.getText().equals(string)){
                    chk.setSelected(true);
                }
            }
        }
        txtNamXuatBan.setText(view.getNxb()+"");
        txtDonGia.setText(view.getGiaNhap()+"");
        cbxNCC.setSelectedItem(view.getNhaCC());
        lblSeri.setText(view.getSeri());
        URL url = getClass().getResource(view.getImg());
        imgAnhSach.setIcon(setsize.setSizeAnh(url, 133, 162));
    }
    private void IconBarcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconBarcodeMouseClicked
        // TODO add your handling code here:
        FrmScanBC.where=0;
        FrmScanBC scan = new FrmScanBC();
        scan.setVisible(true);
    }//GEN-LAST:event_IconBarcodeMouseClicked

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void btnQuanLyThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyThongTinActionPerformed
        // TODO add your handling code here:
        new FrmQuanLyTTSachNhap().setVisible(true);
    }//GEN-LAST:event_btnQuanLyThongTinActionPerformed

    private void rdoDaCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDaCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoDaCoActionPerformed
    public void setDisplay(String id){
        PhieuNhap pn = SERVICE.getByID(id);
        SachCT sachCT = SERVICE_SACHCT.getByID(pn.getIdSachCT());
        lblToday.setText(pn.getNgay()+"");
        lblID.setText(pn.getId());
        if(pn.getTinhtrang()){
            pnPhieuNhap.remove(this.rdoChuaCo);
        }else if(!pn.getTinhtrang()){
            pnPhieuNhap.remove(this.rdoDaCo);
        }
        this.setDisplaySach(sachCT.getSach().getMa(), pn);
    }
    public void checkSach(boolean ft){
        txtMaSach.setText("");
        txtMaSach.setEditable(!ft);
        txtTenSach.setEditable(ft);
        btnTaiAnh.setEnabled(ft);
        btnTacGia.setEnabled(ft);
    }

    public void xemChiTiet(){
        PnThongTinSach.remove(btnTacGia);
        PnThongTinSach.remove(btnHoanThanh);
        PnThongTinSach.remove(IconBarcode);
        PnThongTinSach.remove(btnQuanLyThongTin);
        btnTaiAnh.setEnabled(false);
        txtMaSach.setEditable(false);
        txtNamXuatBan.setEditable(false);
        txtSoLuongNhap.setEditable(false);
        txtDonGia.setEditable(false);
    }

    public static void fillCbxNXB(){
        NhaXuatBanService service = new NhaXuatBanService();
        List<NhaXuatBan>  _lst = service.getAll();
        cbxNhaXuatBan.removeAllItems();
        for (NhaXuatBan nhaXuatBan : _lst) {
            cbxNhaXuatBan.addItem(nhaXuatBan.getTen() +"-"+nhaXuatBan.getDiaChi());
        }
        boxTheLoai.setPreferredSize(new Dimension(WIDTH, boxTheLoai.getHeight()+(boxTheLoai.getComponentCount()/2)*20+5));
    }

    public static void fillCbxNCC(){
        NhaCCService service = new NhaCCService();
        List<NhaCC>  _lst = service.getAll();
        cbxNCC.removeAllItems();
        for (NhaCC nhaCC : _lst) {
            cbxNCC.addItem(nhaCC.getTen()+"-"+nhaCC.getDiaChi());
        }
    }

    public static void fillChkTL(){
        TheLoaiService service = new TheLoaiService();
        List<TheLoaiSach> _lst = service.getAll();
        boxTheLoai.removeAll();
        for (TheLoaiSach theLoaiSach : _lst) {
            JCheckBox chk = new JCheckBox(theLoaiSach.getTen());
            chk.setBackground(Color.white);
            boxTheLoai.add(chk);
        }
    }
    
    public String roleMaPhieuNhap(){
        List<PhieuNhap> _lst = SERVICE.getAll();
        if(!_lst.isEmpty()){
            for (PhieuNhap phieuNhap : _lst) {
                String maphieu = phieuNhap.getMa();
                int max = Integer.parseInt(maphieu.substring(2));
                if(ipn<max){
                    ipn=max;
                }
            }
        }
        ipn++;
        String ma = "PN"+ipn;
        return ma;
        
    }
    
    private String roleMaSach(){
        List<Sach> _lst = SERVICE_SACH.getAll();
        if(!_lst.isEmpty()){
            for (Sach sach : _lst) {
                String maphieu = sach.getMa();
                int max = Integer.parseInt(maphieu.substring(2));
                if(isach<max){
                    isach=max;
                }
            }
        }
        isach++;
        String ma = "MS"+isach;
        return ma;
    }
    
    public Date setNgayNhap(){
        Calendar c = Calendar.getInstance();
        int ngay = c.get(Calendar.DATE);
        int Thang = c.get(Calendar.MONTH)+1;
        int nam = c.get(Calendar.YEAR);
        String date = ngay+"-"+Thang+"-"+nam;
        lblToday.setText(date);
        try {
            return sdf.parse(date);
        } catch (ParseException ex) {
            ex.printStackTrace();
            return null;
        }
    }
    
    private PhieuNhap getPhieuNhapFormData(String idSachCT){
        String ma = roleMaPhieuNhap();
        String ngayNhap = lblToday.getText();
        Boolean tinhTrang = rdoDaCo.isSelected();
        int soLuongNhap = txtSoLuongNhap.getText().equals("")?0:Integer.parseInt(txtSoLuongNhap.getText());
        Double giaNhap = txtDonGia.getText().equals("")?0:Double.valueOf(txtDonGia.getText());
        BigDecimal giaNhapChuan = BigDecimal.valueOf(giaNhap);
        try {
            return new PhieuNhap(null, ma, idSachCT, sdf.parse(ngayNhap), tinhTrang, soLuongNhap, giaNhapChuan);
        } catch (ParseException ex) {
            ex.printStackTrace();
            return null;
        }
    }
    
    private Sach getSachFormData(){
        String ma = roleMaSach();
        String ten = txtTenSach.getText();
        return new Sach(null, ma, ten);
    }
    
    private SachCT getSachCTFormData(Sach sach){
        int namXB = Integer.parseInt(txtNamXuatBan.getText());
        Double giaNhap = Double.valueOf(txtDonGia.getText());
        BigDecimal giaNhapChuan = BigDecimal.valueOf(giaNhap);
        String seri = lblSeri.getText();
        return new SachCT(null, namXB, icon, giaNhapChuan, seri, sach);
    }
    
    private List<TheLoaiSach> getListTheLoai(){
        List<JCheckBox> _lst = new ArrayList<>();
        List<TheLoaiSach> _lstTLS = new ArrayList<>();
        for (int j = 0; j < boxTheLoai.getComponentCount(); j++) {
            _lst.add((JCheckBox) boxTheLoai.getComponent(j));
        }
        for (JCheckBox jCheckBox : _lst) {
            if(jCheckBox.isSelected()){
                String ten = jCheckBox.getText();
                TheLoaiSach tls = SERVICE_TLS.getByName(ten);
                _lstTLS.add(tls);
            }
        }
        return _lstTLS;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconBarcode;
    private javax.swing.JPanel PnThongTinSach;
    public static javax.swing.JPanel boxTheLoai;
    private javax.swing.JLabel btnDong;
    public static javax.swing.JButton btnHoanThanh;
    private javax.swing.JButton btnQuanLyThongTin;
    private javax.swing.JButton btnTacGia;
    private javax.swing.JButton btnTaiAnh;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox<String> cbxNCC;
    public static javax.swing.JComboBox<String> cbxNhaXuatBan;
    private javax.swing.JLabel imgAnhSach;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    public static javax.swing.JLabel lblSeri;
    public static javax.swing.JLabel lblTacGia;
    private javax.swing.JLabel lblToday;
    public javax.swing.JPanel pnPhieuNhap;
    public javax.swing.JRadioButton rdoChuaCo;
    public javax.swing.JRadioButton rdoDaCo;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNamXuatBan;
    public static javax.swing.JTextField txtSoLuongNhap;
    public javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
