/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import DomainModels.DocGia;
import DomainModels.LoiVP;
import DomainModels.PhieuMuon;
import DomainModels.ViPham;
import Services.BaoCaoServices;
import Services.Impl.BaoCaoServicesImpl;
import Services.Impl.DocGiaService;
import Services.Impl.PhieuMuonService;
import Services.Impl.ViPhamService;
import ViewModels.DocGiaViPhamViewModel;
import java.awt.Dimension;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class FrmQuanLyViPham extends javax.swing.JPanel {
    final BaoCaoServicesImpl SERVICE_BC = new BaoCaoServicesImpl();
    final PhieuMuonService SERVICE_PM = new PhieuMuonService();
    final DocGiaService SERVICE_DG = new DocGiaService();
    final ViPhamService SERVICE_VP = new ViPhamService();
    /**
     * Creates new form FrmViPham
     */
    public FrmQuanLyViPham() {
        initComponents();
        this.loadList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        _lstDocGiaViPham = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        _lstDocGiaViPham.setBackground(new java.awt.Color(255, 255, 255));
        _lstDocGiaViPham.setMaximumSize(new java.awt.Dimension(780, 530));
        _lstDocGiaViPham.setPreferredSize(new java.awt.Dimension(780, 530));
        jScrollPane1.setViewportView(_lstDocGiaViPham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadList(){
        List<ViPham> _lstVP = SERVICE_BC.getAll();
        for (ViPham viPham : _lstVP) {
            PhieuMuon pm = SERVICE_PM.getByMa(viPham.getMaPM());
            DocGia dg = SERVICE_DG.getByMa(pm.getDocGia().getMa());
            List<String> _lstLoiVP = new ArrayList<>();
            for (String string : SERVICE_BC.getLoiThuocViPham(viPham.getIdVP())) {
                _lstLoiVP.add(SERVICE_VP.getByid(string).getTen());
            }
            DocGiaViPhamViewModel docGiaViPhamViewModel = new DocGiaViPhamViewModel
            (viPham.getIdVP(), dg.getHoTen(), viPham.getMoTa(), viPham.getHinhPhat(), dg.getImg(), _lstLoiVP);
            FrmDocGiaViPham docGiafrm = new FrmDocGiaViPham();
            docGiafrm.setDisplay(docGiaViPhamViewModel);
            docGiafrm.setPreferredSize(new Dimension(375, 232));
            _lstDocGiaViPham.add(docGiafrm);
            int i = _lstDocGiaViPham.getComponentCount();
            if(i>=4 && i%2==0){
                _lstDocGiaViPham.setPreferredSize(new Dimension(WIDTH, _lstDocGiaViPham.getHeight()+232));
            }
            _lstDocGiaViPham.revalidate();
            _lstDocGiaViPham.repaint();
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _lstDocGiaViPham;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
