/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Utilities.SetSize;
import java.net.URL;

/**
 *
 * @author Admin
 */
public class FrmQuanLyTTSachNhap extends javax.swing.JFrame {
    final SetSize setsize = new SetSize();
    /**
     * Creates new form FrmQuanLyTTSachNhap
     */
    public FrmQuanLyTTSachNhap() {
        this.setUndecorated(true);
        initComponents();
        this.seticon();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnQuanLyTG = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnQuanLyNXB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnQuanLyNCC = new javax.swing.JLabel();
        btnQuanLyTL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnQuanLyTG.setText("jLabel1");
        btnQuanLyTG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyTG.setPreferredSize(new java.awt.Dimension(40, 40));
        btnQuanLyTG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyTGMouseClicked(evt);
            }
        });

        btnClose.setText("jLabel2");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setPreferredSize(new java.awt.Dimension(20, 20));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        jLabel3.setLabelFor(btnQuanLyTG);
        jLabel3.setText("Tác giả");

        btnQuanLyNXB.setText("jLabel1");
        btnQuanLyNXB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyNXB.setPreferredSize(new java.awt.Dimension(40, 40));
        btnQuanLyNXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyNXBMouseClicked(evt);
            }
        });

        jLabel5.setLabelFor(btnQuanLyNXB);
        jLabel5.setText("Nhà xuất bản");

        jLabel6.setLabelFor(btnQuanLyNCC);
        jLabel6.setText("Nhà cung cấp");

        btnQuanLyNCC.setText("jLabel1");
        btnQuanLyNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyNCC.setPreferredSize(new java.awt.Dimension(40, 40));
        btnQuanLyNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyNCCMouseClicked(evt);
            }
        });

        btnQuanLyTL.setText("jLabel1");
        btnQuanLyTL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyTL.setPreferredSize(new java.awt.Dimension(40, 40));
        btnQuanLyTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyTLMouseClicked(evt);
            }
        });

        jLabel9.setLabelFor(btnQuanLyTL);
        jLabel9.setText("Thể loại");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btnQuanLyTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuanLyNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuanLyNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(btnQuanLyTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuanLyTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuanLyNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuanLyNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuanLyTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
        FrmPhieuNhap.fillCbxNCC();
        FrmPhieuNhap.fillCbxNXB();
        FrmPhieuNhap.fillChkTL();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnQuanLyTGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyTGMouseClicked
        // TODO add your handling code here:
        new FrmTacGia().setVisible(true);
    }//GEN-LAST:event_btnQuanLyTGMouseClicked

    private void btnQuanLyNXBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNXBMouseClicked
        // TODO add your handling code here:
        new FrmNhaXuatBan().setVisible(true);
    }//GEN-LAST:event_btnQuanLyNXBMouseClicked

    private void btnQuanLyNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNCCMouseClicked
        // TODO add your handling code here:
        new FrmNhaCungCap().setVisible(true);
    }//GEN-LAST:event_btnQuanLyNCCMouseClicked

    private void btnQuanLyTLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyTLMouseClicked
        // TODO add your handling code here:
        new FrmTheLoai().setVisible(true);
    }//GEN-LAST:event_btnQuanLyTLMouseClicked

    private void seticon(){
        URL urldong = getClass().getResource("/Images/cross-small.png");
        URL urlTG = getClass().getResource("/Images/TacGia.png");
        URL urlTL = getClass().getResource("/Images/TheLoai.png");
        URL urlNCC = getClass().getResource("/Images/NCC.png");
        URL urlNXB = getClass().getResource("/Images/NXB.png");
        btnClose.setIcon(setsize.setSizeAnh(urldong, 20, 20));
        btnQuanLyNCC.setIcon(setsize.setSizeAnh(urlNCC, 40, 40));
        btnQuanLyNXB.setIcon(setsize.setSizeAnh(urlNXB, 40, 40));
        btnQuanLyTG.setIcon(setsize.setSizeAnh(urlTG, 40, 40));
        btnQuanLyTL.setIcon(setsize.setSizeAnh(urlTL, 40, 40));
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnQuanLyNCC;
    private javax.swing.JLabel btnQuanLyNXB;
    private javax.swing.JLabel btnQuanLyTG;
    private javax.swing.JLabel btnQuanLyTL;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
