/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Services.Impl.ThongKeService;
import ViewModels.SachYeuThich;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Admin
 */
public class FrmQuanLyThongKe extends javax.swing.JPanel {
    final ThongKeService service = new ThongKeService();
    /**
     * Creates new form FrmViPham
     */
    public FrmQuanLyThongKe() {
        initComponents();
        this.setTable();
        this.fillcbxMDY(cbxNgayBatDau, cbxThangBatDau, cbxNamBatDau);
        this.fillcbxMDY(cbxNgayKetThuc, cbxThangKetThuc, cbxNamKetThuc);
        this.setTitleBorder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbxThangBatDau = new javax.swing.JComboBox<>();
        cbxNamBatDau = new javax.swing.JComboBox<>();
        cbxThangKetThuc = new javax.swing.JComboBox<>();
        cbxNamKetThuc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        cbxThongKe = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxNgayBatDau = new javax.swing.JComboBox<>();
        cbxNgayKetThuc = new javax.swing.JComboBox<>();

        jRadioButton1.setText("jRadioButton1");

        setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(125, 200, 150));
        jButton2.setText("Excel");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(125, 200, 150));
        jButton3.setText("Word");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbxThangBatDau.setBackground(new java.awt.Color(125, 200, 150));
        cbxThangBatDau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbxThangBatDau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxThangBatDau.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxThangBatDauItemStateChanged(evt);
            }
        });

        cbxNamBatDau.setBackground(new java.awt.Color(125, 200, 150));
        cbxNamBatDau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022" }));
        cbxNamBatDau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxNamBatDau.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNamBatDauItemStateChanged(evt);
            }
        });

        cbxThangKetThuc.setBackground(new java.awt.Color(125, 200, 150));
        cbxThangKetThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbxThangKetThuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxThangKetThuc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxThangKetThucItemStateChanged(evt);
            }
        });

        cbxNamKetThuc.setBackground(new java.awt.Color(125, 200, 150));
        cbxNamKetThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022" }));
        cbxNamKetThuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxNamKetThuc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNamKetThucItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thống kê");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Title"));

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblThongKe.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tblThongKe);

        cbxThongKe.setBackground(new java.awt.Color(125, 200, 150));
        cbxThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống kê sách đang được mượn", "Thống kê đầu sách yêu thích", "Thống kê lỗi vi phạm", "Thống kê nhập sách", "Thống kê độc giả mới" }));
        cbxThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxThongKe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxThongKeItemStateChanged(evt);
            }
        });

        jLabel2.setText("Đến");

        cbxNgayBatDau.setBackground(new java.awt.Color(125, 200, 150));
        cbxNgayBatDau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxNgayKetThuc.setBackground(new java.awt.Color(125, 200, 150));
        cbxNgayKetThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(618, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cbxThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(349, 349, 349)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(cbxNamBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxThangBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbxNamKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxThangKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxThangBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbxThangKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNamKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNamBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
            XSSFWorkbook wordSFWorkbook = new XSSFWorkbook();
            
            XSSFSheet sheet = wordSFWorkbook.createSheet("List Sách Yêu Thích");
            XSSFRow row = null;
            Cell cell = null;
            row = sheet.createRow(3);
            cell =  row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            
            cell =  row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã Sách");
            
            cell =  row.createCell(2, CellType.STRING);
            cell.setCellValue("Tên Sách");
            
            cell =  row.createCell(3, CellType.STRING);
            cell.setCellValue("Lượt Mượn");
            List<SachYeuThich> _lst = service.getSachYeuThich();
            
            for(int i = 0;i< _lst.size();i++){ 
                row = sheet.createRow(4+i);
                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue(i+1);
                
                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(_lst.get(i).getMasach());
                
                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(_lst.get(i).getTenSach());
                
                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(_lst.get(i).getLuotMuon());
            }
            File f  = new File("D://danhSach.xlsx");
            try {
                FileOutputStream fileOutputStream = new FileOutputStream(f);
                wordSFWorkbook.write(fileOutputStream);
                fileOutputStream.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(this," Xuất File Thành Công !!! ");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxThangBatDauItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxThangBatDauItemStateChanged
        // TODO add your handling code here:
        fillcbxMDY(cbxNgayBatDau, cbxThangBatDau, cbxNamBatDau);
    }//GEN-LAST:event_cbxThangBatDauItemStateChanged

    private void cbxNamBatDauItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNamBatDauItemStateChanged
        // TODO add your handling code here:
        fillcbxMDY(cbxNgayBatDau, cbxThangBatDau, cbxNamBatDau);
    }//GEN-LAST:event_cbxNamBatDauItemStateChanged

    private void cbxThangKetThucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxThangKetThucItemStateChanged
        // TODO add your handling code here:
        this.fillcbxMDY(cbxNgayKetThuc, cbxThangKetThuc, cbxNamKetThuc);
    }//GEN-LAST:event_cbxThangKetThucItemStateChanged

    private void cbxNamKetThucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNamKetThucItemStateChanged
        // TODO add your handling code here:
        this.fillcbxMDY(cbxNgayKetThuc, cbxThangKetThuc, cbxNamKetThuc);
    }//GEN-LAST:event_cbxNamKetThucItemStateChanged

    private void cbxThongKeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxThongKeItemStateChanged
        // TODO add your handling code here:
        this.setTitleBorder();
        int i = cbxThongKe.getSelectedIndex();
        if(i==0){
            this.setTableSachDuocMuon();
        }else if(i==1){
            this.setTableSachYeuThich();
        }
    }//GEN-LAST:event_cbxThongKeItemStateChanged

    //Hàm set tiêu đề table
    private void setTitleBorder(){
        String title = (String) cbxThongKe.getSelectedItem();
        TitledBorder boder = (TitledBorder)jScrollPane3.getBorder();
        boder.setTitle(title);
        jScrollPane3.setBorder(boder);
    }
    
    // Hàm set hiển thị và nội dung table
    private void setTable(){
        JTableHeader header = tblThongKe.getTableHeader();
        header.setBackground(new Color(125, 200, 150));
        this.setTableSachDuocMuon();
    }
    
    //hàm lấy mẫu table
    private DefaultTableModel setContentTable(String ...args){
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        for (String arg : args) {
            model.addColumn(arg);
        }
        return model;
    }
    
    //Hàm lấy mẫu table theo sách được mượn
    private void setTableSachDuocMuon(){
        DefaultTableModel model = setContentTable("TÊN ĐỘC GIẢ", "MÃ SÁCH", "TÊN SÁCH", "Số lượng đang mượn");
        tblThongKe.setModel(model);
    }
    
    //Hàm lấy mẫu table theo sách được mượn
    private void setTableSachYeuThich(){
        List<SachYeuThich> _lst = service.getSachYeuThich();
        DefaultTableModel model = setContentTable("MÃ SÁCH", "TÊN SÁCH", "LƯỢT MƯỢN");
        for (SachYeuThich sachYeuThich : _lst) {
            String rowdata[] = {
              sachYeuThich.getMasach(), sachYeuThich.getTenSach(), sachYeuThich.getLuotMuon()+""
            };
            model.addRow(rowdata);
        }
        tblThongKe.setModel(model);
    }
    
    //Hàm fill ngày tháng năm
    private void fillcbxMDY(JComboBox ngay, JComboBox thang, JComboBox nam){
        int check = Integer.parseInt((String) thang.getSelectedItem());
        switch (check) {
            case 1, 3, 5, 7, 8, 10 -> {
                ngay.removeAllItems();
                for (int i = 1; i <= 31; i++) {
                    ngay.addItem(i);
                }
            }
            case 4, 6, 9, 11 ->{
                ngay.removeAllItems();
                for (int i = 1; i <= 30; i++) {
                    ngay.addItem(i);
                }
            }case 2 ->{
                int checkNam = Integer.parseInt((String) nam.getSelectedItem());
                if((checkNam%4==0 && checkNam%100!=0) || (checkNam%400==0)){
                    ngay.removeAllItems();
                    for (int i = 1; i <= 29; i++) {
                        ngay.addItem(i);
                    }
                }else{
                    ngay.removeAllItems();
                    for (int i = 1; i <= 28; i++) {
                        ngay.addItem(i);
                    }
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxNamBatDau;
    private javax.swing.JComboBox<String> cbxNamKetThuc;
    private javax.swing.JComboBox<String> cbxNgayBatDau;
    private javax.swing.JComboBox<String> cbxNgayKetThuc;
    private javax.swing.JComboBox<String> cbxThangBatDau;
    private javax.swing.JComboBox<String> cbxThangKetThuc;
    private javax.swing.JComboBox<String> cbxThongKe;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblThongKe;
    // End of variables declaration//GEN-END:variables
}
