/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.CuonSach;
import DomainModels.Sach;
import DomainModels.SachCT;
import Services.Impl.CuonSachService;
import Services.Impl.KhoSachServices;
import Services.Impl.SachCTService;
import Services.Impl.SachService;
import Services.KhoSachService;
import Utilities.SetSize;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import static java.awt.image.ImageObserver.WIDTH;
import java.net.URL;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Admin
 */
public class FrmSachCanThay extends javax.swing.JFrame {
    final SetSize setsize = new SetSize();
    final SachService SERVICE_SACH = new SachService();
    final SachCTService SERVICE_SACHCT = new SachCTService();
    final CuonSachService SERVICE_CS = new CuonSachService();
    public static int where = 0;
    /**
     * Creates new form FrmSachCanThay
     */
    public FrmSachCanThay() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTable(tblSachCanThay);
        this.seticon();
        this.loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSachCanThay = new javax.swing.JTable();
        btnClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sách cần thay", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblSachCanThay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng", "Số lượng  tình trạng dưới 50%"
            }
        ));
        tblSachCanThay.setGridColor(new java.awt.Color(255, 255, 255));
        tblSachCanThay.setSelectionBackground(new java.awt.Color(125, 200, 150));
        tblSachCanThay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachCanThayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSachCanThay);

        btnClose.setText("jLabel1");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setPreferredSize(new java.awt.Dimension(20, 20));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void tblSachCanThayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachCanThayMouseClicked
        // TODO add your handling code here:
        int row = tblSachCanThay.getSelectedRow();
        KhoSachService ksSV = new KhoSachServices();
        FrmSach fmrSach = new FrmSach();
        fmrSach.setSachCanThay();
        fmrSach.setDisplay(ksSV.getKhoSachView((String) tblSachCanThay.getValueAt(row, 0)));
        fmrSach.setVisible(true);
        where =1;
        this.dispose();
    }//GEN-LAST:event_tblSachCanThayMouseClicked

    public void setTable(JTable table) {
        Font bigFont = new Font("Segoe UI", Font.PLAIN, 14);
        table.getTableHeader().setFont(bigFont);
        table.getTableHeader().setPreferredSize(new Dimension(WIDTH, 32));
        table.setRowHeight(28);

        JTableHeader header = table.getTableHeader();
        header.setBackground(new Color(125, 200, 150));
        header.setForeground(Color.white);

    }
    
    private void seticon() {
        URL urldong = getClass().getResource("/Images/cross-small.png");
        btnClose.setIcon(setsize.setSizeAnh(urldong, 20, 20));
    }
    
    public void loadTable(){
        int count = 0;
        DefaultTableModel model = (DefaultTableModel) tblSachCanThay.getModel();
        model.setRowCount(0);
        List<Sach> _lstSach = SERVICE_SACH.getAll();
        for (Sach sach : _lstSach) {
            SachCT sachct = SERVICE_SACHCT.getByIDSach(sach.getId());
            List<CuonSach> _lstCS = SERVICE_CS.getByIDSachCT(sachct.getId());
            for (CuonSach cuonSach : _lstCS) {
                if(cuonSach.getTinhTrang()<=50){
                    count++;
                }
            }
            if(count==0){
                continue;
            }
            Object rowData[]={
                sach.getMa(), sach.getTen(), _lstCS.size(), count
            };
            model.addRow(rowData);
        }
        tblSachCanThay.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSachCanThay;
    // End of variables declaration//GEN-END:variables
}
